browser: 'chrome'
headless: false
use_profile_directory: false
use_proxy: false
path_to_profile_dir: '/Users/macbook/Library/Application Support/Google/Chrome/parser2/'
proxy_host: '127.0.0.1'
proxy_port: '8080'
